[package]
name = "ascent"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3"
uuid = { version = "1.13", features = ["v4"] }
rand = "0.9"
